export const SUPABASE_URL = process.env.REACT_APP_SUPABASE_URL || '';
export const SUPABASE_ANON_KEY = process.env.REACT_APP_SUPABASE_ANON_KEY || '';
export const CLOUDINARY_CLOUD_NAME = process.env.REACT_APP_CLOUDINARY_CLOUD_NAME || 'dbaw8elnt';
export const CLOUDINARY_UPLOAD_PRESET = process.env.REACT_APP_CLOUDINARY_UPLOAD_PRESET || 'vintage_media';
export const CLOUDINARY_API_KEY = process.env.REACT_APP_CLOUDINARY_API_KEY || '542659795359421';
export const CLOUDINARY_API_SECRET = process.env.REACT_APP_CLOUDINARY_API_SECRET || '7gTk_EqO3GLBuAeK6oUraStoQ74'; 